/////////////////////////////////////////////////////////////////////////////////////////
//   Demonstration of use of OdometryMouse.c Include file
//
/////////////////////////////////////////////////////////////////////////////////////////
#pragma config(Sensor, dgtl2,  cntreset,       sensorTouch)
#pragma config(Sensor, dgtl9,  xquad,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, yquad,          sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "OdometryMouse.c"

#define datalog

task main()
{
	BotLocation p;
	init_odometry(xquad,yquad);
	while (1==1)
	{
		get_botlocation(&p);
		writeDebugStream("%f %f\r",p.x_pos,p.y_pos);
	}
}
